### ISSUE TITLE
unable to run unit test seperately 

### ISSUE THREAD

**Issue by longuyen1** [chrisshayan/TechLooper#492]
Trying to run unit test with this method: 
SuggestionServiceImplTest.suggestSkills()

Error while running unit test without Elastic search turn on:
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:305)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:200)
	at org.elasticsearch.client.transport.support.InternalTransportClient.execute(InternalTransportClient.java:106)
	at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:338)
	at org.elasticsearch.client.transport.TransportClient.search(TransportClient.java:430)
	at org.elasticsearch.action.search.SearchRequestBuilder.doExecute(SearchRequestBuilder.java:1112)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65)
	at com.techlooper.service.impl.SuggestionServiceImpl.suggestSkills(SuggestionServiceImpl.java:40)
	at com.techlooper.service.impl.SuggestionServiceImplTest.testSuggestSkills(SuggestionServiceImplTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)

SearchResponse searchResponse = transportClient.prepareSearch("suggester").setTypes("skill")
        .setQuery(QueryBuilders.matchAllQuery())
        .addSuggestion(skillNameSuggest).execute().actionGet();

Solution:
Apply mockito with  transportClient.prepareSearch() to return test data.

**Comment by khoa-nd** [comment]
Hi Long,
Thank for your feedback. You're right. This is really a integration test rather than an unit test. We should have added more unit test cases based on your solution above. :)
